config/routes.rb
RGAmazon::Application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations',:omniauth_callbacks => "users/omniauth_callbacks" }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

    root to: 'home#index'

    resources :books
    resources :authors
    resources :categories
    resources :users, only: [:edit, :update, :destroy]
    resources :orders, only: [:index, :show, :update, :edit]
    resources :adresses
    resource :cart do
      post 'empty', to: 'carts#empty'
    end
    resources :order_items, only: [:create, :update, :destroy]

  end

  get '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
  get '', to: redirect("/#{I18n.default_locale}")

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
    respond_to do |format|
      format.html
      format.json { render json: @order_items }
    end
  end
  def empty
    current_order.order_items.destroy_all

    redirect_to :back, notice: "Your cart empty"

  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart_row.html.haml
.well
  .row
    .col-xs-8
      =image_tag book.image_url(:thumb)
      %h4= book.title

    .col-xs-4
      = form_for order_item do |f|
        %h4.text-right
          Unit Price:
          %span{:style => "color: green"}= number_to_currency order_item.price
        .row
          .col-xs-4.group
            .input-group
              = f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1,max: book.stock
          .col-xs-8.text-right
            .btn-group
              = f.submit "Update Quantity", class: "btn btn-primary"
              = f.hidden_field :book_id, value: book.id

              = link_to "Delete", order_item, { data: { confirm: "Are you sure you wish to delete the book '#{order_item.book.title}' from your cart?" }, method: :delete, class: "btn btn-danger" }
        %h4.text-right
          Total Price:
          %span{:style => "color: green"}= number_to_currency order_item.total_price

app/views/carts/_shopping_cart.html.haml
- if !@order_item.nil? && @order_item.errors.any?
  .alert.alert-danger
    %ul
      - @order_item.errors.full_messages.each do |msg|
        %li= msg
- if @order_items.size == 0
  %p.text-center
    There are no books in your shopping cart.  Please #{link_to "go back", root_path} and add some books to your cart.
- else
  - @order_items.each do |order_item|
    = render 'carts/cart_row', book: order_item.book, order_item: order_item, show_total: true

  - if current_user
    =link_to  'Checkout' ,edit_order_path(current_user.id), class: "btn btn-default"

  - else
    = link_to "Checkout", new_user_registration_path, { data: { confirm: "You Must Signup or Login! Sign up now?" }, class: "btn btn-default" }

  = link_to "Empty cart" ,empty_cart_path , { data: { confirm: "Are you sure you wish to delete all books from your cart?" }, method: :destroy_all, class: "btn btn-danger" }
  = link_to 'continue shopping',books_path , class: "btn btn-default"
  = form_for :coupon do |c|
    = c.text_field '',:placeholder =>'Coupon code'
    = c.button :submit

app/views/carts/show.html.haml
.shopping-cart
  = render "shopping_cart"