config/routes.rb
RGAmazon::Application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations',:omniauth_callbacks => "users/omniauth_callbacks" }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

    root to: 'home#index'

    resources :books
    resources :authors
    resources :categories
    resources :users, only: [:edit, :update, :destroy]
    resources :orders, only: [:index, :show, :update, :edit]
    resources :adresses
    resource :cart do
      post 'empty', to: 'carts#empty'
    end
    resources :order_items, only: [:create, :update, :destroy]

  end

  get '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
  get '', to: redirect("/#{I18n.default_locale}")

end

app/views/layouts/_cart.html.haml
%li.nav.nav-pills{:role => "tablist"}
  %li.active{:role => "navigation"}
    %a.cart{:href => cart_path}
      %span.glyphicon.glyphicon-shopping-cart{"aria-hidden" => "true"}

      %span.badge #{current_order.order_items.size} total
      %span.badge  #{number_to_currency current_order.subtotal}

app/views/layouts/_messages.html.haml
- flash.each do |type, message|
  %div{:class => "alert #{alert_class_for(type)} alert-dismissible fade in"}
    %span.close{"data-dismiss" => "alert",class: "close", :"aria-hidden" => "true"} ×
    %span.sr-only Close
    = message

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "/"} Home
    / Collect the nav links, forms, and other content for toggling

    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          = link_to "Library",books_path
        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            Category
            %b.caret
          %ul.dropdown-menu{:role => "menu"}
            - Category.all.each do |category|
              %li
                %a= link_to_unless_current "#{category.title}", books_path(category: category)

      %form.navbar-form.navbar-left{:role => "search"}
        .form-group
          %input.form-control{:placeholder => "Search", :type => "text"}
        %button.btn.btn-default{:type => "submit"} Submit
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li= link_to "Hello #{current_user.first_name}",edit_user_path(current_user)
          %li= image_tag(current_user.avatar.url) if current_user.avatar?
          %li= link_to 'Logout', destroy_user_session_path, :method => :delete
          %li= link_to "Admin panel", rails_admin.index_path('Book') if current_user.admin?
        - else
          %li
            %a{:href => new_user_session_path} Login
          %li
            %a{:href => new_user_registration_path} Registration
          %li

        %li.pull-right
          = render 'layouts/cart'
        %li.dropdown.pull-right
          %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            Language
            %span.caret
          %ul.dropdown-menu{:role => "menu"}
            %li
              %a= link_to_unless_current raw("English"), locale: "en"
            %li
              %a= link_to_unless_current raw("Russian"), locale: "ru"

%nav.navbar-inner

app/views/layouts/application.html.haml
!!!
%html
  %head
  %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
  %title= content_for?(:title) ? yield(:title) : "RGAmazon"
  %meta{:content => content_for?(:description) ? yield(:description) : "RGAmazon", :name => "Book store"}
    = stylesheet_link_tag :application, :media => "all"
    = javascript_include_tag :application
    = csrf_meta_tags
    = yield(:head)
  %body
    = render 'layouts/navbar'
    .container
  #main{:role => "main"}
    .container
    .content
    .row
    .span12
    = render 'layouts/messages'
    = yield
  %footer